package files;

import parser.tokens.Token;
import parser.tokens.TokenType;
import parser.utils.StringUtils;

import java.io.*;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.List;
import java.util.ListIterator;

public class MultistyleFile {

    private final Path inputFilePath;
    private List<Token> tokens;

    public MultistyleFile(String path) throws IOException {
        this.inputFilePath = Paths.get(path);
        this.tokenizeFile();
    }

    private List<String> readFile() throws IOException {
        File file = new File(this.inputFilePath.toUri());
        if (!file.exists()) {
            throw new FileNotFoundException("Failed to found file " + this.inputFilePath);
        }

        List<String> content = new ArrayList<>();

        try (BufferedReader reader = new BufferedReader(new FileReader(file))) {
            reader.lines()
                    .forEach((line) -> {
                        if (!line.isEmpty() || !line.isBlank()) {
                            content.add(line.trim());
                        }
                    });
        } catch (Exception e) {
            throw new IOException("Failed to read path " + this.inputFilePath);
        }
        return content;
    }

    private void tokenizeFile() throws IOException {
        List<String> fileContent = this.readFile();

        List<Token> tokens = new ArrayList<>(fileContent.size() + 1);

        ListIterator<String> iterator = fileContent.listIterator();
        while (iterator.hasNext()) {
            int line = iterator.nextIndex() + 1;
            String item = iterator.next();

            // Single > means that it is a block opening/closing tag e.g. <colors>
            // Two > means that it is a block item e.g. <foo>#bazz</foo>
            int closing = StringUtils.countOccurrences(item, ">");
            if (closing == 1) {

                if (item.contains("/")) {
                    tokens.add(TokenType.colorBlockClose(line));
                } else {
                    tokens.add(TokenType.colorBlockOpen(line));
                }

            } else if (closing == 2) {
                String name = item.substring(
                        item.indexOf("<") + 1,
                        item.indexOf(">")
                );

                String value = item.substring(
                        item.indexOf(">") + 1,
                        item.lastIndexOf("<")
                );

                // TODO: handle unrecognized tokens
                Token token = switch (name) {
                    case "colors" -> TokenType.colorBlockOpen(line);
                    case "/colors" -> TokenType.colorBlockClose(line);
                    default -> TokenType.colorItem(line, name, value);
                };

                tokens.add(token);
            }
        }
        this.tokens = tokens;
        return tokens;
    }

    public void outputFile(OutputMode mode) throws IOException {
        // TODO: add more build modes
        switch (mode) {
            case css -> this.outputCss();
        }
        System.out.println("[INFO]: multistyle file was exported to " + mode + "successfully");
    }

    private void outputCss() throws IOException {
        StringBuilder output = new StringBuilder();
        output.append("/* Generated by multistyle tool */\n\n");
        output.append(":root {\n");

        List<Token> items = this.tokens.stream()
                .filter((token -> token.type == TokenType.ColorItem))
                .toList();

        for (Token item : items) {
            output.append("\t--" + item.name + ": " + item.raw + ";\n");
        }
        output.append("}");

        Path outputPath = Paths.get(this.inputFilePath.getParent().toString(), "output.css");

        File file = new File(outputPath.toUri());
        if (!file.exists()) {
            file.createNewFile();
        }

        try (FileWriter writer = new FileWriter(file)) {
            writer.write(output.toString());
        }
    }

    // public only for development
    public void displayTokens() {
        for (Token token : this.tokens) {
            System.out.println(
                    "[TOKEN " + token.type + "]: " + token.name + " - " + token.raw + " at line " + token.line
            );
        }
    }
}
